name: lua_dardo
description: A Lua virtual machine written in Dart, which implements Lua5.3 version.
version: 0.0.5
publish_to: none
homepage: https://github.com/arcticfox1919/LuaDardo.git

environment:
  # sdk: '>=2.12.0 <3.0.0'
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  sprintf: ^7.0.0

dev_dependencies:
  lints: ^2.0.0
  pedantic: ^1.11.1
  test: ^1.17.12
